Import("env", "IS_WIN")
cloned_env = env.Clone()
SRC_TRIANGLE = ["triangle.c"]
TRI_DEFINES=["TRILIBRARY", "NO_TIMER", "GCC_FPU_CONTROL", "POINTERS_ARE_VERY_LONG"]
cloned_env.Append(CPPDEFINES=TRI_DEFINES)
cloned_env.Append(CCFLAGS=["-fPIC"])
libtriangle = cloned_env.Library(target=env["libtri"], source=SRC_TRIANGLE)
