# Build libtripy
Import("env", "IS_WIN", "TRIANGLE_DIR")
cloned_env = env.Clone()
SRC_INDEX = ["_tri.c","trig_index.c"]
cloned_env.Append(LIBPATH=[TRIANGLE_DIR])
cloned_env.Append(CPPPATH=[TRIANGLE_DIR])
libtripy = cloned_env.SharedLibrary(target=env["libtripy"], source=SRC_INDEX, LIBS=[env["libtri"]])
Return("libtripy")

